services:
  blip-erp-backend:
    image: blip-erp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - blip-erp-db
    environment:
      - DATABASE_URL=postgres://blip-erp-db:5432/blip_erp
      - DATABASE_USER=blip_erp
      - DATABASE_PASSWORD=blip_erp
      - DATABASE_NAME=blip_erp
      - DATABASE_HOST=blip-erp-db
      - DATABASE_PORT=5432

  blip-erp-mysql-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  blip-erp-cassandra-db:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=blip_erp
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
    volumes:
      - ./cassandra-data:/var/lib/cassandra
